declare module '@bldr/icons'
declare module '@bldr/shortcuts'
declare module '@bldr/modal-dialog'
declare module '@bldr/media-client'
declare module 'vue-native-websocket'
declare module '@bldr/components-collection'
